class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if user == nil
      flash[:error] = "Email does not exist"
    elsif user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:message] = "Congratulations, you successfully signed in"
    else
      flash[:error] = "Password is invalid"
    end
    redirect_to root_path
  end

  def create_from_omniauth
    # after the omniauth from facebook is returned, u put it inside auth_hash
    # authentication checks if user was already created in authentication table and tries to retreive it by
    # provider name (e.g. Facebook) and the user id of your profile used in facebook
    # If not it creates a new authentication class for use later
    auth_hash = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
    if authentication.user
      @user = authentication.user
      authentication.update_token(auth_hash)
      # token is a form of string and generated by facebook after successfull authentication, can do things on behalf of users
      # (e.g. post status etc.)
      flash[:message] = "You're signed in again with fb"
    else
      @user = User.create_with_auth_and_hash(authentication,auth_hash)
      flash[:message] = "Signed in first time with facebook"
    end
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:message] = "You successfully signed out!"
    redirect_to root_path
  end
end
